# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: alpine:latest
    steps:
      - run: echo $Name
  print_world:
    docker:
      - image: alpine:latest
    steps:
      - run: echo world
  save_hello_world_output:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "text to output" >output.txt
      - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - target/output.txt
  print_output:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          - at: /tmp/workspace/
      - run: cat target/output.txt

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - save_hello_world_output
      - print_output:
          requires:
            - save_hello_world_output